name: EXAM CD YML FILE

on:
  pull_request:
    types: [ closed ]
    branches: [ develop ]
  push:
    branches: [ develop ]

jobs:

  build:
    name: build and zip
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Make zip file
        run: zip -r PROJECT_NAME.zip build/libs appspec.yml scripts   // 압축시 빌드된 jar파일과 appspec, scripts만 압축

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: S3 Upload
        run: aws s3 cp PROJECT_NAME.zip s3://${{secrets.AWS_BUCKET}}

  deploy:
    needs: build
    name: deploy to ec2
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Code Deploy
        run: aws deploy create-deployment --application-name PROJECT_NAME --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name CODE_DEPLOY_GROUP --s3-location bucket=${{secrets.AWS_BUCKET}},bundleType=zip,key=PROJECT_NAME.zip --region ${{secrets.AWS_REGION}} --file-exists-behavior OVERWRITE

